# https://github.com/jest-community/eslint-plugin-jest
plugins:
  - jest
  - fp
env:
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base
  - "plugin:jest/recommended"
  - "plugin:fp/recommended"

overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0 # TODO: remove when rule will be adjusted for new nodejs version (issue link?)
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutating-methods:
    - error
    - allowedObjects:
      - "_"